<?php
/**
 * Created by PhpStorm.
 * User: 韩令恺
 * Date: 2018/5/25 0025
 * Time: 17:57
 */

namespace app\shop\controller;
use Think\Db;
use think\Session;

class CashController extends BaseController
{
    public $url = '';
    public $authStatus = array(0 => '未认证', 1 => '已认证');
    public $userType = array(1 => '小程序用户', 2 => '生活号用户');
    public $payType = array(1 => '微信', 2 => '支付宝');
    public $orderType = array(1=>'订单消费',2=>'充值');
    public $id;
    public $type;
    public function _initialize()
    {
        parent::_initialize();
        // TODO: Change the autogenerated stub
        $this->url = request()->root(true) . '/public/';
        $this->type = Session::get('MMS.type');//子后台登录帐号类型（1：商家 2：员工）
        if($this->type == 1){
            $aid=Session::get('MMS.uid');
            $this->id=Db::name('shop')->where(['aid'=>$aid])->value('shop_id');//商家ID
        }else{
            $this->id = Session::get('MMS.uid');//员工ID
        }
        $this->assign('type',$this->type);
    }



    //财务列表
    public function index(){

        $payType = array(1=>'微信',2=>'支付宝',3=>'余额');
        $condition = null;

        if ($_GET['nickname']){
            $condition['b.nickname'] = ['like','%'.trim($_GET['nickname']).'%'];
            $this->assign('nickname',$_GET['nickname']);
        }

        if ($_GET['mobile']){
            $condition['b.mobile'] = ['like','%'.trim($_GET['mobile']).'%'];
            $this->assign('mobile',$_GET['mobile']);
        }

        if ($_GET['user_type']){
            $condition['b.user_type'] = $_GET['user_type'];
            $this->assign('user_type',$_GET['user_type']);
        }

        if ($_GET['type']){
            $condition['a.type'] = $_GET['type'];
            $this->assign('type',$_GET['type']);
        }
        $pagesize =   self::$MMS['set']['pagesize']?:20;
        $page = input('page')?input('page'):1;

            $condition['a.shop_id']=$this->id;//商家
            $result = Db::name('cash_log')->alias('a')->join('user b','a.user_id=b.user_id','LEFT')
                ->where($condition)
                ->field('a.*,b.nickname,b.mobile,b.user_type')
                ->page($page,$pagesize)
                ->order('a.ctime desc')
                ->select();

            foreach ($result as $k=>$v){
                $result[$k]['user_type'] = $this->userType[$v['user_type']]; //用户类型
                $result[$k]['type'] = $this->orderType[$v['type']]; //订单类型
                $result[$k]['pay_type'] = $payType[$v['pay_type']]; //支付方式
            }
            $count = Db::name('cash_log')->alias('a')->join('user b','a.user_id=b.user_id','LEFT')->where($condition)->count();

        $this->getPage($count, $pagesize, 'App-loader', '财务列表', 'App-search');
        $this->assign('orderType',$this->orderType);
        $this->assign('userType',$this->userType);
        $this->assign('result',$result);
        echo $this->fetch();
    }


    //财务详情
    public function detail(){

        echo $this->fetch();
    }



    public function exportSelect(){
        // $device = M('device')->field('device_id,title')->order('device_id desc')->select();
        // $user    = M('user')->field('user_id,nickname')->where(array('nickname'=>array('NEQ',"")))->order('user_id desc')->select();
        // $this->assign('device', $device);
        echo $this->fetch('exportSelect');
    }

    public function exportexcel()
    {
        header("Content-type:application/octet-stream");
        header("Accept-Ranges:bytes");
        header("Content-type:application/vnd.ms-excel");
        header("Content-Disposition:attachment;filename=财务列表.xls");
        header("Pragma: no-cache");
        header("Expires: 0");

        $payType = array(1=>'余额',2=>'微信',3=>'支付宝');

        $condition = null;
        if (input('nickname')){
            $condition['b.nickname'] = ['like','%'.input('nickname').'%'];
        }
        if (input('mobile')){
            $condition['b.mobile'] = ['lick','%'.input('mobile').'%'];
        }
        if (input('user_type')){
            $condition['b.user_type'] = input('user_type');
        }
        $title = ['编号','用户昵称','用户手机','用户类型','支付方式','财务类型','金额','支付时间'];
        $field = ['a.order_number','b.nickname','b.mobile','b.user_type','a.pay_type','a.type','a.money','a.ctime'];
        $data = Db::name('cash_log')->alias('a')->join('user b','a.user_id=b.user_id')->where($condition)->field($field)->select();
        foreach ($data as $k=>$v){
            $data[$k]['nickname'] = $v['nickname']?$v['nickname']:'未设置昵称';
            $data[$k]['mobile'] = $v['mobile']?$v['mobile']:'未绑定手机';
            $data[$k]['user_type'] = $this->userType[$v['user_type']];
            $data[$k]['pay_type'] = $payType[$v['pay_type']];
            $data[$k]['ctime'] = date('Y-m-d H:i:s',$v['ctime']);
        }


        //导出xls 开始
        if (!empty($title)) {
            foreach ($title as $k => $v) {
                $title[$k] = iconv("UTF-8", "GB2312", $v);
            }
            $title = implode("\t", $title);
            echo "$title\n";
        }
        if (!empty($data)) {
            foreach ($data as $key => $val) {
                foreach ($val as $ck => $cv) {
                    $data[$key][$ck] = (string)(' '.(string)iconv("UTF-8", "GB2312", $cv).' ');
                }
                $data[$key] = (implode("\t", $data[$key]));
            }
            echo implode("\n", $data);
        }

    }



}

