<?php
/**
 * Created by PhpStorm.
 * User: 韩令恺
 * Date: 2018/5/21 0021
 * Time: 9:48
 */

namespace app\wxsite\controller;
use think\Db;

class PayController extends BaseController
{

    public $appUrl = "";
//    public function _initialize()
//    {
//        parent::_initialize(); // TODO: Change the autogenerated stub
//    }


    public function api(){
        $api_name = input('api_name');
        $this->user_id = $this->get_user_id();
        if ($api_name){
            switch ($api_name){
                case 'recharge':
                    $this->recharge();//充值
                    break;
                default:
                    $info['code'] = 404;
                    $info['msg'] = '接口不存在';
                    return $info;
                    break;
            }
        }else{
            $info['code'] = 404;
            $info['msg'] = '接口不能为空';
            $info['data'] = $api_name;
            return $info;
        }

    }



    //充值
    public function recharge(){
        $pay_type = input('pay_type');
        $money = input('money');
        if(empty($pay_type)) $this->_return(-1,'支付类型不能为空',(object)array());
        if(empty($money)) $this->_return(-1,'支付金额不能为空',(object)array());
        // if (!$_POST['money'] || !$_POST['pay_type']) $this->_return(-1,'缺少参数');
        $token = input('token');
        $user_id = $this->get_user_id();
        $rechargeData = array(
            'order_number'  =>  'CZ'.time().rand(1000,9999),
            'user_id'       =>  $this->user_id,
            'pay_type'      =>  $pay_type,
            'money'         =>  $money,
            'status'        =>  1,
            'ctime'         =>  time()
        );
        $money = 0.01;
        switch ($pay_type) {
            case '1'://微信充值
                    $res = Db::name('recharge')->insert($rechargeData);
                    if(!$res) $this->_return(-1,'充值数据新增失败',(object)array());
                    $order = new OrderController();
                    $order->wxpay($rechargeData['order_number'],$money,$token);
                break;
            case '2'://支付宝充值
                    $res = Db::name('recharge')->insert($rechargeData);
                    if(!$res) $this->_return(-1,'充值数据新增失败',(object)array());
                    $data['body'] = '支付宝消费订单'.$rechargeData['order_number'];
                    $data['out_trade_no'] =$rechargeData['order_number'];
                    $data['subject'] = '支付宝付款';
                    $data['total_amount'] = floatval($money);//总金额
                    $data['notify_url'] = "http://".$_SERVER['HTTP_HOST']."/wxsite/alipay/order_notify_url";
                    // $data['']
                    $form = model('Alipay')->alipay($data);
                    // var_dump($form);die;
                    // header('Location:'.$form);
                    echo $form;
                break;
            default:
                $this->_return(-1,'支付类型不对',(object)array());
                break;
        }
    }


}













