<?php
/**
 * Created by PhpStorm.
 * User: 马远利
 * Date: 2018/5/21 0021
 * Time: 22:30
 */

namespace app\wxsite\controller;
use think\Db;

class TemplateController extends BaseController
{

   public $appUrl = "";
   public function _initialize()
   {
       parent::_initialize(); // TODO: Change the autogenerated stub
   }

   //发送模板消费
   public function sendTemplate()
   {

   }
   
}













